### ISSUE TITLE
Add support for English and German

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#1]
As a user, I want to be able to switch the language from English to German and otherwise by clicking a button in the navigation bar. 
As a dev, I want an easy way to implement dual language.

### Dependencies

Depends on:

-  #29
-  #28

### Definition of Done

- [ ] By clicking the button, a change between English and German for all texts on all pages for one session,
- [ ] There is one central location for all texts of one language. 

### Storypoints

8

**Comment by navetis** [comment]
Implemented in #50
