### ISSUE TITLE
Add E-Mail dispatch

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#10]
As a developer, I want a function which allows me to send an E-Mail to a given address. This is for the reminder feature when a user has an overdue with an asset.

### Definition of Done

- [ ] The function sends an e-mail to the given e-mail address.
- [ ] The subject and text of the e-mail can be changed. 
- [ ] The E-Mail is sent from a system email account, e.g. 'noreply@asset-management.com'.

**Comment by gruendlich** [comment]
Beware: Test currently only check that mails are built correctly. Testing the actual sending of a mail would be a pain, which is why we decided against it. Looking back, it might have made sense to test successful authentication.
