### ISSUE TITLE
Add multi-language support for item details page

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#100]
As a user I want to switch the language on the item details page by clicking the button (flag) in the navbar. Also, I want the language to stay consistent throughout the app. The languages supported languages are German and English.

### Dependencies

Depends on:

- #8 
- #49
- #64 

### Acceptance Criteria

- [x] Clicking the button in the navbar changes the language on the page between German and English
- [x] The language that was used before going to the asset details screen, will be the one shown when first opening the asset details screen
- [x] If the language was changed in the item details screen, the same language will be used in the pages I visit after

**Comment by DefineDan** [comment]
Maybe take a how this team did it #84

**Comment by Tonybodo** [comment]
Estimation: S
