### ISSUE TITLE
Use common Design and Components for Item Details Screen

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#101]
As a user, I want to have the same navbar in the item details screen as in the other screens. Also, I want the design of the Elements (Texts, Buttons, etc.) to be consistent with the other pages.

### Dependencies

Depends on:

- #107 
- Common Navbar component
- Style Guide [Styleguide_DE.pdf](https://github.com/hpi-swt2/bookkeeper-portal-red/files/10114800/Styleguide_DE.pdf) [Styleguide_EN.pdf](https://github.com/hpi-swt2/bookkeeper-portal-red/files/10116269/Styleguide_EN.pdf)

**Comment by Tonybodo** [comment]
Estimation: S

**Comment by DefineDan** [comment]
Es wird anscheinend eine Person geben, die global irgendwelche Designeinstellungen vornimmt. Bis dahin müsst ihr erstmal nichts am Design ändern. Ich verlinke das entsprechende Issue, sobald es vom anderen PO erstellt wurde
