### ISSUE TITLE
Add user membership management to group management

### ISSUE THREAD

**Issue by Encotric** [hpi-swt2/bookkeeper-portal-red#106]
As a group owner, I would like to have buttons per user and a single button to remove or add users to my group. This should be possible on the group management page.

The "Nutzer hinzufügen" button should open a modal window that requires entering the user's email address and shows an error alert box when no user matches this email address after I submit. Otherwise, the user will be added to the group and I will be redirected to my group management page seeing that the user is now in the member list.

The small red button next to every group member in the member list should remove the desired group member from the group. After removal, the membership list should be updated for the group owner.

![Add user modal](https://user-images.githubusercontent.com/27862794/204628945-e9e1b713-df95-4b94-84e0-2548e8e772fb.png)
![User not found while adding](https://user-images.githubusercontent.com/27862794/204628969-c8944359-a370-4ae8-be86-34493f7186b7.png)

### Dependencies

Depends on:

- #6 

### Acceptance Criteria

- [ ] Only the group owner is able to add or remove users from his group
- [ ] Users are members of the group after the group owner adds them to it
- [ ] Users are no longer members of a group after a group owner removes them from his group
- [ ] When a user is not found while trying to add him/her to a group, an error message is shown and the group owner can retry
- [x] Button to message group member is working (#267)
- [ ] Add user email form field should be email type
- [ ]

**Comment by kbroschke** [comment]
Should the owner of a group see the “remove this user”-button for his own entry?
If yes, what should happen if the button is clicked?
If no, should the “message this user”-button also be removed?

**Comment by Encotric** [comment]
@kbroschke The owner should not see the remove user button. Moreover, the contact button should also be hidden for the owner. An owner could only delete his group or (in the future) set a new owner and leave the group.
