### ISSUE TITLE
Add Lending Process: Self-borrowing

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#11]
As a user that wants to borrow an asset, I can, after I scanned its QR code, click on a borrow button on the asset details page if the asset is available or reserved by me. When I click this, the asset is officially borrowed by me and unavailable to others. The borrowing ends when I return the asset. I should do this before the end of the max. borrowing period, which was set by the asset owner.

### Dependencies

Depends on:

- #8 
- #16 
- #30

### Definition of Done

- [x] Conditional borrow option on asset details page (only after scanning)
- [x] I can borrow when the asset is reserved by me or when it is available (and I did not reserve)
- [x] Borrowed assets are assigned to the borrower
- [x] Borrowed assets are unavailable to others
- [x] Tag on Asset Detail Page should display "Borrowed by me" when I am currently borrowing the item

![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63105659/201535306-688935f7-9b4a-449f-a9c4-b1c3b286e751.png)
![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63105659/201535312-eb7ff3c7-0e7d-407c-8f9b-02b70fb5946d.png)

**Comment by TimRiedel** [comment]
### Requirements from developers view

A user is able to see the "lending" button, if:
- [ ] he has "lending" permission rights
- [ ] the item is currently not reserved by someone else
- [ ] the item is not borrowed by someone else


A user can click on "lend", if:
- [ ] the item is reserved by him
    - the user has an active reservation of the item with `start_date <= today <= end_date`
- [ ]  the item is lendable.
    - an item is lendable if no lending with the `item.id` exists that has a `completed_date == null`
    - Someone can still borrow the item until the next reservation


When a user clicks on "lend", then
- [ ] a lending record is created
    - `due_date` is either the `start_date` of the next reservation or `today + item.max_borrowing_period`
    - `started_at` is now
    - `user_id` of current user
    - `item_id` of the item
    - `completed_at` is null
- [ ] a popup confirms the lending
- [ ] the button name changes to "return"

**Comment by TimRiedel** [comment]
Hey Tony, Johanna und ich haben etwas weiter dran gearbeitet und sind wie immer schleppend voran gekommen. Hier sind Todos, die noch offen sind aus der heutigen Session:

- [ ] pass current user to `is_borrowed_by(user)` method
- [ ] fix `is_lendable` method and its test
- [ ] fix `is_reserved_by(user)` method
- [ ] add test for `is_reserved_by(user)` method
- [ ] make button invisible if the the item is borrowed by someone else
- [ ] make button visible only if current user has lending rights

**Comment by TimRiedel** [comment]
Hi @DefineDan wir fragen uns gerade was passieren soll, wenn der Nutzer bspw. eine Reservierung hat, das Item dann jedoch vorzeitig zurückgibt. Soll es dann ab dem Rückgabezeitpunkt für andere Nutzer wieder verfügbar sein, sprich die Reservierung wird gecancelt?

**Comment by TimRiedel** [comment]
Hi @richartkeil, we had a look into the data model and wondered if there was a specific reason to allow `nil` values for the `starts_at, ends_at` attributes of a `reservation` as well as the `started_at` attribute of a `lending`? This will be the main way  of determining if a user has reserved or borrowed an item at the moment, so `nil` values would add a lot of edge cases to the business logic.

**Comment by DefineDan** [comment]
> Hi @DefineDan we are just wondering what should happen if the user has a reservation, for example, but then returns the item early. Should it then be available again for other users from the time of return, i.e. the reservation is cancelled?

I'm not sure if I get it. The reservation will be valid for a fixed amount of time. The user has no option to extend it. After this fixed time period, the reservation will get cancelled automatically. We don't need an option for the user to cancel his reservation manually. If a user has reserved an item and now borrows it, the reservation will be cancelled as well, so the reservation can't ever continue after I return the item. After returning the item, it should directly be available for other users again. Is that what you meant?

**Comment by richartkeil** [comment]
> Hi @richartkeil, we had a look into the data model and wondered if there was a specific reason to allow nil values for the starts_at, ends_at attributes of a reservation as well as the started_at attribute of a lending? This will be the main way of determining if a user has reserved or borrowed an item at the moment, so nil values would add a lot of edge cases to the business logic.

Oh, no there is no reason for that. As long as there should be no such thing as permanent reservations (without end date) you can just create a migration that removes the `nil` option.

**Comment by TimRiedel** [comment]
> If a user has reserved an item and now borrows it, the reservation will be cancelled as well, so the reservation can't ever continue after I return the item. After returning the item, it should directly be available for other users again. Is that what you meant?

@DefineDan Yes thats exactly what I meant, thanks!

**Comment by TimRiedel** [comment]
@richartkeil Thanks, I created a pull request for that #83
