### ISSUE TITLE
Home screen follow Up

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#120]
As a User, I want a consistent layout. Therefor, the QR-Code should always be visible. Also, the sidebar should be smaller. Replace the current HPI logos with the attached **SVGs**. Other minor corrections can be found in the acceptance criteria.

### Dependencies

Depends on:

- #28 
- #29 

### Acceptance Criteria

- [ ] The sidebar length correlates with the largest option title in the sidebar. 
- [ ] Remove the label "Neu inseriert"
- [ ] Make sure that the QR code functionality works on both navBar versions.
- [ ] Remove NavBar option **home**.
- [ ] Ensure that the footer does not fill the whole page, if it is empty (e.g. by using a placeholder)
- [ ] Integrate the given SVGs

## HPI logos
[hpi-logos.zip](https://github.com/hpi-swt2/bookkeeper-portal-red/files/10194181/hpi-logos.zip)

**Comment by leonardhorns** [comment]
Please make sure the functionality of the button is also available in both versions as this feature will be merged by the end of this sprint.
-> #125

**Comment by bweengener** [comment]
@Alorcus Can you provide an uncorrupted version of the logos, please?



![Image](https://user-images.githubusercontent.com/47246301/206865704-b0c40ea7-82a2-474b-b404-b94f608dd0ed.png)

![Image](https://user-images.githubusercontent.com/47246301/206865705-181e10db-c832-4fe6-9036-92bd95934d96.png)

**Comment by Alorcus** [comment]
Oh sorry, hope this works now?

[logos.zip](https://github.com/hpi-swt2/bookkeeper-portal-red/files/10202753/logos.zip)
