### ISSUE TITLE
Add to items details page: item edit, delete, QR-print buttons

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#128]
As an item owner (someone with item management rights), I have buttons on the items details page for editing or deleting the item and printing its QR code. As a user who is not part of the owner group I don't have these buttons. 

When I click delete, I want to have a popup (or similar) to confirm the deletion, so I don't delete accidentally. The edit button will redirect to the item edit page.

### Dependencies

- #8 
- #4 
- Unstyled Edit and QR button links already exist on the page

### Acceptance Criteria

- [ ]  Functional edit, delete and QR-print buttons when user is item owner
- [ ] No edit and delete buttons when user is not item owner

![Image](https://user-images.githubusercontent.com/63105659/206922668-8eff32d2-d0e5-43b4-8b65-d3a5a72b42af.jpg)
![Image](https://user-images.githubusercontent.com/63105659/206922669-fe0e6253-d39d-4fdb-933d-6eeb1d890290.jpg)

**Comment by TimRiedel** [comment]
Hey, bevor ihr mit der Arbeit hier anfangt, schließt euch mal mit @LeoKohlenberg kurz, die haben bei sich ein ähnliches Issues #131. Bzw. denke ich dass unser Issue auf deren Issue eine Dependency hat, weil die sich allen Buttons annehmen.

**Comment by DefineDan** [comment]
AW @FSadrieh : Wenn ich es richtig sehe fügt ihr in eurem issue wirklich funktionalität hinzu. #131 macht nur die Buttons schön und wird dann ein Template in den Discord schicken. Das heißt euer issue ist schon anders

**Comment by LeoKohlenberg** [comment]
Wenn ihr schnell seid müsst ihr auch nicht auf mich warten mit dem Ticket und könnt das auch mit hässlichen Buttons umsetzen, ich würde das schön machen dann für euch nachholen als Teil meines Tickets. Wenn ich vorher fertig bin wärs cool, wenn ihr den Style direkt übernehmt.

**Comment by richartkeil** [comment]
Estimate: M
