### ISSUE TITLE
Add auto notification

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#13]
As an owner of an asset, I want my assets back after the lending period. Therefore, the following notifications get sent to the lending user:
- reminder notification, one day before the return
- reminder notification, one day after overdue date
- weekly reminder notification if an asset has an overdue

### Dependencies

Depends on:

- #10
- #11 

### Definition of Done

- [x] Notifications get only send, if the asset has not returned.
- [ ] Each E-Mail communicates the issue and names the owner of the asset.

**Comment by Durborough** [comment]
Looks like this can be implemented using cron jobs in rails.
We need to make sure these cron jobs also work on our host. Heroku for example does something fishy here...
https://gorails.com/forum/how-can-i-send-emails-30-days-before-the-time-limit-in-rails
https://dev.to/christensenjoe/scheduling-tasks-in-rails-with-the-whenever-gem-7a6

**Comment by Durborough** [comment]
This has been implemented using rake Tasks. The rake tasks need to be manually schedueled in Heroku. This is quite annoying since it cannot be done automatically but Heroku doesn't allow to use the rails schedueler.

The defined rake tasks need to be performed daily.

**Comment by Durborough** [comment]
This is blocked until deployed on Heroku. We have to scheduele the rake tasks on Heroku. This can be easily done and doesn't take that much time.

**Comment by gruendlich** [comment]
Scheduling of implemented tasks via Heroku seems to work. Small fix regarding weekly overdue reminders was merged. Other changes now belong to new tickets.
Moving ticket to done.
