### ISSUE TITLE
Add to item details page: Info on how to borrow or return

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#144]
As a user, I want to find out how to borrow or return an item in the case where I did not scan its QR-code. So in the case where I don't have the borrow or return button I want to have an infobox instead, telling me how to borrow or return.

If I could borrow the item, but didn't scan the QR-code I want the text 1 displayed. 
If I could return the item, but didn't scan the QR-code I want the text 2 displayed. 

### Resources

Text 1: How to borrow this item? Use your mobile device to scan the QR-code of this item. You will find the item at the location below.

Text 2: How to return this item? Use your mobile device to scan the QR-code of this item. You will find the item at the location below.

Use DeepL for German translations of the texts.

Maybe use the info card bootstrap component: https://getbootstrap.com/docs/4.0/components/card/#using-custom-css

![Borrow Instructions](https://user-images.githubusercontent.com/63105659/206909236-f10e00ad-d9d7-4c22-b4f0-3d27be291868.jpg)

For mobile, put this info box above the item description, or what you think looks better. 

### Dependencies
- #8 
- #67 

### Acceptance Criteria

- [x]  When borrow button can't be seen, because of missing ?src=qrcode param, display text 1 instead
- [x]  When return button can't be seen, because of missing ?src=qrcode param, display text 2 instead

**Comment by richartkeil** [comment]
Estimate: M

**Comment by johannaschlimme** [comment]
Hi @DefineDan, soll die Infobox zu Borrow zusammen mit dem Reservieren-Button sichtbar sein oder nur zwischen Reservierung und QR-Code-Scan?

**Comment by DefineDan** [comment]
Nur zwischen Reservierung und QR-Code scan reicht. Also so wie ihr es jetzt habt.

**Comment by DefineDan** [comment]
Schafft ihr das vor der Zwischenpräsi noch auf Dev zu mergen (also morgen oder Sa)? Würde glaube ich beim Verständnis helfen und sieht nett aus.

**Comment by TimRiedel** [comment]
Ja ich arbeite jetzt am Review!

> Schafft ihr das vor der Zwischenpräsi noch auf Dev zu mergen (also morgen oder Sa)? Würde glaube ich beim Verständnis helfen und sieht nett aus.
@DefineDan Ja ich reviewe es jetzt!
