### ISSUE TITLE
Fix uniform time datatypes in item

### ISSUE THREAD

**Issue by TimRiedel** [hpi-swt2/bookkeeper-portal-red#147]
As a developer I want to use uniform Time datatypes within the database. Especially when using dates in the reservation or lending, ruby stores dates in "UTC" by default and we should use `Time.current` according to [this article](https://thoughtbot.com/blog/its-about-time-zones) to avoid time zone errors.

### Dependencies 
- #9

**Comment by richartkeil** [comment]
Estimate: XS

**Comment by richartkeil** [comment]
Review by @janiswehen
