### ISSUE TITLE
Fix language selection

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#149]
A GET parmater in the url (e.g. http://localhost:3000/items/new?item_type=movie) is overwritten when cahanging the language type. This should be fixed by preserving the current GET paramters.

http://localhost:3000/items/new?item_type=movie
changes to:
http://localhost:3000/items/new?locale=en

It should be:
http://localhost:3000/items/new?item_type=movie&locale=en

**Comment by Alorcus** [comment]
Finished with https://github.com/hpi-swt2/bookkeeper-portal-red/pull/130

**Comment by Alorcus** [comment]
Made a mistake. This is not Done. Sorry!
