### ISSUE TITLE
Add info and status for missing borrowing permission

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#151]
As a user, I want to find out that I don't have the permission to reserve/borrow an item. 

On the item details page instead of a borrow/reserve button I have an info field with Text1. Also the status badge of the item will say "no access" in red. The same status "no access" should be present in the item preview (item cards on home sceen) when I am missing borrowing rights.

### Resources

Text1: Why can't I borrow this item? You are not part of a group that is allowed to borrow this item.

Use DeepL for German translation

Style of info field similar to #144 

### Dependencies

#8 
#89 

### Acceptance Criteria

When user doesn't have borrowing permissions
- [ ]  text1 is displayed instead of the usual borrow/reserve button on item details screen
- [ ] status badge says "no access" on item details screen
- [ ] status in item preview (item cards) says "no access" on home and /items screens

**Comment by DefineDan** [comment]
Split from #69

**Comment by richartkeil** [comment]
Estimate: S

**Comment by richartkeil** [comment]
Review by @konrad-gerlach
