### ISSUE TITLE
Set permissions

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#153]
As a User with management permission, I want a UI, which enables me to set all permission types for each group.
It's enough to select one permission-type for full specification:

The management permission includes the lending permission.
The lending permission includes the view permission.

### Resources
![Full HD](https://user-images.githubusercontent.com/63072611/207277875-964c5d97-d393-4d69-b57e-4bee98a81fe3.png)
![Full HD](https://user-images.githubusercontent.com/63072611/207277901-ec124df5-e301-48ac-805a-018daec558d1.png)

### Completes

Attention! There are already existing (UI) functionalities to set permissions. Reuse it, if possible!

- #65 
- #76 
- #85 

### Acceptance Criteria

- [ ] All groups can be selected.
- [ ] A permission gets deleted, if a user clicks on the cross.
- [ ] A new permission gets added if I click on “Add new Permission”.
- [ ] A group can be set/changed with a click on the left field of a permission.
- [ ] A permission-type of a group can be set/changed with a click on the right field of a permission.

**Comment by Yannis-Hofmann** [comment]
Corresponding PR: https://github.com/hpi-swt2/bookkeeper-portal-red/pull/223

**Comment by Yannis-Hofmann** [comment]
The internationalization on the permission level has to be added. @bweengener it sounded as if you had an idea how to do this in the last meeting

**Comment by bweengener** [comment]
For the migration script, we can use the following snippet, when the group name is known. Is `everyone` the correct title?

```sql
INSERT INTO permissions(item_id, group_id, permission_type, created_at, updated_at)
SELECT id, (
    SELECT groups.id
    FROM groups
    WHERE groups.name = 'everyone'
    LIMIT 1),
    0,
    datetime(),
    datetime()
FROM items;
```

We can use `execute` within a migration class in order to execute this SQL Insert.

cc @Yannis-Hofmann , @matveysiva
