### ISSUE TITLE
New Add Item Button Mobile

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#161]
As a User I want to be able to easily add a new Item when using my mobile device. Therefore an easily accessible button should be added. This button should always be displayed on the bottom right of the Screen, floating above the pages content. 

The floating button should contain a "plus" icon and have the secondary color as a background. The Botton is displayed whenever items are shown on the screen. I.E. when the grid view of items is shown.

### Acceptance Criteria
- [x] The add new Item Button is shown on every page containing the item grid view.
- [x] Clicking the button triggers the same drop down menu as before, allowing the user the select an item type.

**Comment by MaxSpeer** [comment]
![Image](https://user-images.githubusercontent.com/82819900/207567370-1958c0a5-24b0-42c5-bfd0-c90eb614653a.png)

**Comment by MaxSpeer** [comment]
![Image](https://user-images.githubusercontent.com/82819900/207567503-f1ffebfc-bc76-474c-ac54-0e8658cd2b47.png)

The button's position should be similar to this.

**Comment by MaxSpeer** [comment]
https://codepen.io/androidcss/pen/yOopGp

The button should look like this, but with a different color.

**Comment by MaxSpeer** [comment]
estimate 8

**Comment by gwauge** [comment]
Resolved by #197
