### ISSUE TITLE
Sort by Drop Down for universal grid view

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#163]
As a User I want to be able to sort the grid view. Therfore I want to select an order for the item grid view.
Possible sort criteria should be:
- alphabetical
- newly added
- availibility

The sorting itself is part of another issue. #164

The drop down menu should be a bootstrap dropdown with the info color.

### Acceptance Criteria
- [x] A drop down Menue is shown on top of the item grid view.
- [x] Selecting one of the items adds the sort order as a get parameter and reloads the page.

**Comment by MaxSpeer** [comment]
![Image](https://user-images.githubusercontent.com/82819900/207580943-72ac67f2-22f3-4fe6-90f0-031501039c33.png)

**Comment by MaxSpeer** [comment]
A similar feature (filter for item category) is still pending due to failing tests. #212

**Comment by MatthiasCr** [comment]
what does "sort by availibility" mean for us? Show all available items first and then all unavailible?
