### ISSUE TITLE
Fix static links to ruby path

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#165]
As a user, I want to be able to keep my query parameters, while browsing through the site.

<MockUps>

### Dependencies

Depends on:

- #112 

### Acceptance Criteria

- [ ]  The links behind buttons are done with ruby path so that the parameters are stored

**Comment by Pungitius** [comment]
see [https://stackoverflow.com/questions/3762430/rails-preserving-get-query-string-parameters-in-link-to](https://stackoverflow.com/questions/3762430/rails-preserving-get-query-string-parameters-in-link-to)
