### ISSUE TITLE
Make Create / Edit Screens look good

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#169]
As a User I want the Create and Edit Screen to look good.
Therefore bootstrap design should be implemented for the two pages.

**Comment by gwauge** [comment]
@MaxSpeer gefällt dir das so oder hättest du es gerne anders?

| Alt | Neu |
| --- | --- |
| ![item-form-old](https://user-images.githubusercontent.com/55636135/209439160-4f2542b6-6a51-4a4b-bd8a-b6ffdfba6655.png) |  ![item-form-new](https://user-images.githubusercontent.com/55636135/209439155-9266ffb1-73cc-46f6-b450-3d50d80d399a.png) |

Wenn man auf das jeweilige Label klickt, wird jetzt auch das passende Feld darunter fokussiert.
Wenn es dir so passt, würde ich das gleiche für alle Item Types machen.

**Comment by MaxSpeer** [comment]
Sieht gut aus @gwauge.
