### ISSUE TITLE
Limit length of database objects

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#172]
As a user, I want to be able to have a nicely formatted website. Right now, long group, item names or descriptions will break the style. 

### Dependencies

Depends on:

- #94 

### Acceptance Criteria

- [x]  Group and item names are limited
- [ ] The amount of groups with permissions is limited
- [x] The description is limited

**Comment by gwauge** [comment]
@MaxSpeer, sollen die Datenbankfelder in der Länge limitiert sein (also bspw. der Itemname darf max. 250 Zeichen haben) oder soll einfach nur die Anzeige abgeschnitten werden, wenn der Name zu lang ist (bspw: "Sehr langer Nam...")?

Falls ersteres der Fall ist: was für Limits erdenkst du für sinnvoll für die einzelnen Felder?

**Comment by MaxSpeer** [comment]
Hier sollen die Datenbankfelder begrenzt sein. 
Strings auf 100 Zeichen. Ausnahme: Description des Items: 1500
