### ISSUE TITLE
Add Lending Process: Waiting List

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#18]
As a user that wants to borrow an item that is currently unavailable, I have the option to sign up for a waiting list. As soon as the item is available again, the item gets reserved by the first user in the waiting list automatically and the user gets removed from the list.

As an item owner, I will always be placed at the head of the waiting list.

### Dependencies

- #8 
- #16 
- #9 

### Definition of Done

- [ ] Button on item details page to sign up to waiting list if item unavailable
- [ ] Automatic reservation like described above

**Comment by Tonybodo** [comment]
Nicht im Scope notification für die Reservierung.
Keine Einsicht für das managen der Listen in denen man Eingetragen ist.

**Comment by richartkeil** [comment]
Implementation Idea:
- Model `WaitingEntry` stores user, item and creation date
- if item is currently reserved by someone, instead a button "Join Waitlist" appears → when clicked, a `WaitingEntry` will be created
- if reservation period of previous user ends or the previous user returns the item, the system will automatically create a reservation for the next waiting entry
