### ISSUE TITLE
Add necessity to login via HPI-Email

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#19]
As a user, I want to be able, to login with my HPI-Email to the website, so that I can participate in the lending process and can manage my own assets.

### Dependencies

- #22 
- #41 

### Definition of Done

- [ ] only HPI-Emails are allowed to login
- [ ] an error message appears if Email or password is mismatches/don't exist
- [ ] every Email generates a unique account solely accesible to the person with the login credentials (every accont is uniquely identifiable e.g. with a user_id)

**Comment by Skn0tt** [comment]
addressed by https://github.com/hpi-swt2/bookkeeper-portal-red/pull/62
