### ISSUE TITLE
Add ability to tag groups

### ISSUE THREAD

**Issue by Encotric** [hpi-swt2/bookkeeper-portal-red#20]
As a user, I want to know which groups of users are officially created or maintained by the HPI to validate that I am interacting with the right group. Therefore, every official group should have a verification mark next to its name whenever it is displayed. 

Additionally, I would like to determine not only if a group is verified, but also if a group is tagged as a user group. Therefore, a group should be able to have exactly one of the tags `verified`, `user`, or `none` (tag names only for demonstration purposes; you are free to change them). Only the `verified` tag should have a verification mark.

### Dependencies

Depends on:

- #5 

### Acceptance criteria

- [x] UI design: A verification mark icon must be on the right side of the official group's name whenever it is displayed
- [x] Connected to group management implementation in the backend

**Comment by TobiPeterG** [comment]
Development in #192
