### ISSUE TITLE
CSV Export Frontend

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#207]
As a user, I want to be able to click a button that triggers the export. Only desktop. Next to the filter button

![Image](https://user-images.githubusercontent.com/73780962/211341676-5bf42aa0-d39e-446c-a0f0-7daa53e85f49.png)

### Dependencies

Depends on:

- #208

### Acceptance Criteria

- [ ]  On button click the export is triggered

**Comment by leonardhorns** [comment]
Extra issue is redundant as this is easily implemented while testing backend.
