### ISSUE TITLE
Fix: Matching colors of status badge in items overview

### ISSUE THREAD

**Issue by johannaschlimme** [hpi-swt2/bookkeeper-portal-red#209]
Currently the colors of the status badges in the items card overview page don't change as in the item details view. The colors of the badges should be matching with the colors on the item detail view.

![Image](https://user-images.githubusercontent.com/78924632/211003482-f150db07-7f29-4352-b4a9-69a15434f0c5.png)

![Image](https://user-images.githubusercontent.com/78924632/211004088-20d9156e-380c-4b19-86e3-4320e50a2ce2.png)

**Comment by johannaschlimme** [comment]
@DefineDan Is it okay if the status badge on the item grid looks the same as on the item detail view or should it only be the text (not a badge) as can be seen in the image in the description? 


![Image](https://user-images.githubusercontent.com/78924632/212436081-b77a1f8b-a288-46ed-99f6-5202516b262e.png)

**Comment by DefineDan** [comment]
@johannaschlimme Sure, please keep the badge on the grid view, it looks way better :)
