### ISSUE TITLE
Add Analytics page

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#210]
As a user I want to access a page, where I can see various analytics regarding various items.

For Mock-Up scroll down.

### Dependencies
- #42 
- #23 

### Acceptance Criteria
- [x] button to access page should be on profile
- [x] mobile and desktop version of this page is working
- [x] style mostly matches the Mock-Up
- [x] page should be available in German and English 

![Image](https://user-images.githubusercontent.com/66786380/211013496-678449c6-7fa1-4fe1-9568-7b76ccd59e5b.jpg)

Example of Analytics page:

![Image](https://user-images.githubusercontent.com/66786380/211013931-bceef2bd-5718-458b-b40e-225a412e1cd0.jpg)

**Comment by phkeese** [comment]
Closed by #249 and #250
