### ISSUE TITLE
Setup Heroku  Dev App for Dev Deployment

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#216]
As a Product Owner, I want to be able to check the current state of the dev branch. Therefore, an additional Heroku App with the Dev Branch is needed. For further information, please contact @chrisma.

### Acceptance Criteria

- [ ] The Dev branch is accessible via a Heroku App, like the Main Branch.

**Comment by Alorcus** [comment]
If you have any further questions, feel free to ask @FSadrieh.

**Comment by chrisma** [comment]
You need Heroku credentials to create another deployment. As deployments on Heroku incur costs, we are trying to limit the amount of collaborators with administrative access to the Heroku platform. Please contact me via Discord to receive the credentials. Thanks!
