### ISSUE TITLE
Add a login screen for desktop

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#22]
As a user, I want to be able, to have site on desktop where I can login, so that the login process is facilitated.

For Mock-Up scroll down

### Dependencies

- none

### Definition of Done

- [ ] a dedicated site where I can login with my HPI-Email (HPI OpenID Connect; path should be something like [url.de]/login) exists
- [ ] the style matches the theme of HPI/ Mock-Ups

Example Login with HPI-Moodle on desktop:
![Image](https://user-images.githubusercontent.com/66786380/201487281-3f9d3b1b-656e-48d4-96fe-cb38fa12374f.png)

![Image](https://user-images.githubusercontent.com/66786380/201487292-b2ad240a-0a69-452f-9afb-336ca7e38ca0.png)

Homescreen of website (for style orientation):

![Image](https://user-images.githubusercontent.com/66786380/201492497-981444e2-87b3-417c-bd91-98457c3e739e.png)

Colors to use:

![Image](https://user-images.githubusercontent.com/66786380/201765751-31bae738-8b44-409c-a61a-e4497612f844.png)

**Comment by Skn0tt** [comment]
addressed by https://github.com/hpi-swt2/bookkeeper-portal-red/pull/62
