### ISSUE TITLE
Small rework on the nav bar elements

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#229]
Currently, my asset does nothing. It should link to the 'My assets' page (https://bookkeeper-red-main.herokuapp.com/items/my).  In addition, it should be renamed to 'My items'. Also, the “Categories” element has no function. It can be removed.

![grafik](https://user-images.githubusercontent.com/63072611/211339256-264b6025-7669-4359-93e9-fe616be070b0.png)

In the mobile version, it is currently not possible to navigate to the home screen. Therefore, add a new button in the nav bar that points to the home screen. 

![grafik](https://user-images.githubusercontent.com/63072611/211337618-83a074f0-4892-4cd3-a2b6-624d9ad46aa4.png)

### Acceptance Criteria

- [x] The button 'My Assets' links to the given link.
- [x] Rename 'My Assets' to 'My Items.
- [x] The button 'Categories' has been removed.
- [x] The new button is labled 'Home'
- [x] The new button should only be displayed in 'mobile mode' as shown above

**Comment by EliasNotFound** [comment]
Finished with #270
