### ISSUE TITLE
Add history of borrowers for item details page

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#230]
As a user I want to view the history of a specific item directly on the items detail page for convenience.

### Dependencies
- #63 
- #8 

### Acceptance Criteria
- [ ] if i am on a detail page of an item, I can see the history of borrowers of that item like in #225

**Comment by gwauge** [comment]
@Ngo-Tuan-Kiet soll das einsehbar für jeden auf der Seite jedes Items sein? Geht das datenschutzrechtlich klar?

**Comment by DefineDan** [comment]
> @Ngo-Tuan-Kiet soll das einsehbar für jeden auf der Seite jedes Items sein? Geht das datenschutzrechtlich klar?

@gwauge the history of borrowers on the item page should only be visible for users who have can_manage permission for that item. So if a user only has can_lend or can_view permissions, he won't see the history on the items page
