### ISSUE TITLE
Add Create Item Button to Navigation Bar in Desktop view

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#237]
As a User I want to be able to add Items easily. Therefore the create item button shown on the search page should be replaced by a similar button with the same functionality in the navigation bar. 

![image](https://user-images.githubusercontent.com/82819900/211586666-00c2206b-ac87-45a4-927d-70a7deda6475.png)

### Dependencies

None.

### Acceptance Criteria

- [x]  The Navigation bar contains a new nav-item "Create Item" / "Item erstellen" with a dropdown menu including (Book, Movie, Game, Other)
- [x]  Clicking an item type opens the create page for that item type.
- [x] The obsolete create item button on the item search page is removed.

**Comment by simon-weissmueller** [comment]
Is the Create Item Button also desired for mobile? Dropdown on mobile navbar seems kinda odd.

Note: ignore the spacing, that will be fixed

![Image](https://user-images.githubusercontent.com/62717141/214027095-d2700e4c-4347-4686-8c5c-b52067ea4d57.png)

**Comment by MatthiasCr** [comment]
I'm no PO but I think that's not necessary, since we already have that yellow circle button in the bottom right corner on mobile

**Comment by simon-weissmueller** [comment]
Whats your opinion @MaxSpeer?

**Comment by MaxSpeer** [comment]
I agree with @MatthiasCr. The floating button on mobile is sufficient. Therefore the this button should only be visible in the desktop nav bar.

**Comment by simon-weissmueller** [comment]
Aye Sir 🫡
