### ISSUE TITLE
Fix search and language selection

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#240]
A GET parmater in the url (e.g. http://localhost:3000/?locale=de) is overwritten when searching. This should be fixed by preserving the current GET paramters.

http://localhost:3000/items/new?locale=de
changes to:
http://localhost:3000/items?q%5Bname_or_description_cont%5D=who&button=search

It should be:
http://localhost:3000/items?q[name_or_description_cont]=who&button=search&locale=de

**Comment by FSadrieh** [comment]
Looks similar to [#149](https://github.com/hpi-swt2/bookkeeper-portal-red/issues/149)

**Comment by Alorcus** [comment]
> Looks similar to [#149](https://github.com/hpi-swt2/bookkeeper-portal-red/issues/149)

Why did you open the ticket again?

**Comment by Alorcus** [comment]
Oh my bad! I mixed up tickets.

**Comment by Alorcus** [comment]
I close this ticket and reopen the original.
To provide a clear track for the dependencies.

**Comment by Alorcus** [comment]
Possible approach:
![Image](https://user-images.githubusercontent.com/63072611/212916755-9ca37244-6332-4e8c-8ba8-991a3813c54c.png)
