### ISSUE TITLE
Add phone number to profile page

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#25]
As a user, I want to be able, to add my phone to my profile and see the phone number of others (if provided), so that contacting others becomes more easy.

### Dependencies

- #23 

### Definition of Done

- [x] I can add my own phone number to the profile page
- [x] the phone number is then displayed on my profile page

**Comment by Alorcus** [comment]
This ticket is done. But in dev-deployment, I can't save my phone number?

**Comment by MatthisCl** [comment]
> This ticket is done. But in dev-deployment, I can't save my phone number? @MatthisCl

Works when i pull dev locally, are there diffs in the deployed version?

**Comment by Alorcus** [comment]
> > This ticket is done. But in dev-deployment, I can't save my phone number? @MatthisCl
> 
> Works when i pull dev locally, are there diffs in the deployed version?

As I wrote, it is not possible to save a phone number. You can test it in the dev deployment (https://bookkeeper-red-dev.herokuapp.com/)

**Comment by MatthisCl** [comment]
> > > This ticket is done. But in dev-deployment, I can't save my phone number? @MatthisCl
> > 
> > 
> > Works when i pull dev locally, are there diffs in the deployed version?
> 
> As I wrote, it is not possible to save a phone number. You can test it in the dev deployment (https://bookkeeper-red-dev.herokuapp.com/)

I know, just wondering whats different in the deployed version, Will look into it
