### ISSUE TITLE
Cascading permissions

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#269]
As a user, I want to have a cascading permission system:

Every user that can_manage an item also can_borrow and can_view this item.
Every user that can_borrow an item also can_view this item.

### Dependencies

Depends on:
- #86 
- #69 
- #75 
- #153 (might be conflicting)

### Acceptance Criteria

- [x]  Every user that can_manage an item also can_borrow and can_view this item
- [x]  Every user that can_borrow an item also can_view this item

**Comment by DefineDan** [comment]
We have to keep an eye on how #153 is implemented, so that we don't rebuild or destroy logic they thought of.

**Comment by johannaschlimme** [comment]
When the cascading permissions were added, please also change parts of the code where multiple permissions were set at once to get all permissions. For example see Tims comment on #283.
