### ISSUE TITLE
Add the 'everyone'-group

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#276]
URGENT: Integration by Jan. 19 (before Main deployment) would be great!
-----
As an item owner, I want to be able to set permissions for all users on the platform. This requires a group that includes all users on bookkeeper red.

### Dependencies

- #5 
- #7 

### Acceptance Criteria

- [x] Every user is in the 'everyone' group. Attention: new users should also be members. 
- [x] The group behaves like any other group, it's possible to add the group to an item with a specific permission.
- [x] The 'everyone'-group is not shown up on the group page.
- [x] Make sure that the group is available in the master as well.

**Comment by WilliamBrandt** [comment]
view in pullrequest #352

**Comment by EliasNotFound** [comment]
finished in #352
