### ISSUE TITLE
Set 'everyone'-group as default

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#277]
As an item creating user, I want the process to be fast and secure. Therefore, the default permission is: 'everyone' 'can_borrow'. This ensures that an item is visible and lendable by everyone by default. 

![grafik](https://user-images.githubusercontent.com/63072611/213016095-2377b1fe-f24c-4818-aaeb-271d3147e76d.png)

### Dependencies

- #276 
- #153 

### Acceptance Criteria

- [ ] The described permission is set when a new item is created.
- [ ] It's possible to change or remove the permission.
- [ ] The permission will not be set a second time by default (e.g., If I remove it, save it and edit it again)

**Comment by Yannis-Hofmann** [comment]
Is already solved in #223
