### ISSUE TITLE
Add Homescreen Desktop

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#28]
As a User, I need a home screen to have consistent access to the asset management platform.
The home screen displays all assets.

![Full HD](https://user-images.githubusercontent.com/63072611/201522977-bfe7445a-ba27-4e2d-8c2c-7ef07234f6dd.png)

### ACs

- [ ] The desktop home screen is displayed on tablet and PC
- [ ] It's possible to scroll, if and only if the screen is too small.

**Comment by Durborough** [comment]
The current issues with overflow on the right hand side, can be fixed as follows:

In `index.html.erb` change `<div class="mx-5">` to `<div class="mx-auto">`. But this doesn't fix the scrolling issue completely. So you have to wrap the row bootstrap class into a [wrapper container](https://stackoverflow.com/questions/27758457/how-to-remove-this-horizontal-scrollbar-in-bootstrap-3).

**Comment by navetis** [comment]
Für mich zur Orientierung: wann werdet ihr mit der finalen Navigationbar fertig? :)

**Comment by Skn0tt** [comment]
Same, we're blocked on this in https://github.com/hpi-swt2/bookkeeper-portal-red/issues/82 :)

**Comment by Durborough** [comment]
This Feature isn't tested for various reasons:
1. tests would just test Bootstrap functionality
2. tests would just test Browser funktionality
Thus tests wouldn't provide value. So if testing is needed please feel free to add it in a place where it can be found. For further questions please just contact Team Kraken.
