### ISSUE TITLE
Add Homescreen mobile

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#29]
As a User, I need a home screen to have consistent access to the asset management platform.
The home screen displays all assets.

![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63072611/201524371-611c2558-d7fd-48c3-ac74-07001ef93974.png)

![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63072611/201524382-b7abfbed-63db-46f6-9e4f-70707e7e403c.png)

### Definition of Done

- [ ] The mobile home screen is displayed on smartphones.
- [ ] It's possible to scroll, if and only if the screen is too small.
- [ ] The sidebar can be opened with a swipe to the right or a click on the menu icon.

**Comment by Durborough** [comment]
Fixed the bug by adjusting `application.scss` with `@media (max-width: $mobileDeviceCutoff) {
  .navbar-collapse {
    top: 56px;`

**Comment by EliasNotFound** [comment]
The estimate for sprint 1 for this task was 8. Some testing and small adjustments still have to be done in sprint 2 and have been estimated with 5 story points.

**Comment by bweengener** [comment]
Changelog:
- Added labels to `bell` and `human` in mobile-view

![Image](https://user-images.githubusercontent.com/47246301/206037895-739bdab1-c23b-473f-a4a4-9a0d53569ccd.png)

As this is cross-cutting, I committed this directly on `dev`.

**Comment by navetis** [comment]
Bei mir sieht die nav bar so aus. Trotz letztem commit. Soll das so? 
![image](https://user-images.githubusercontent.com/78549340/206171673-d32537e3-dc25-42c1-834a-921f79a4f48d.png)

**Comment by navetis** [comment]
![image](https://user-images.githubusercontent.com/78549340/206171984-3e26f82c-998a-4c5c-846c-32bb2fef6b25.png)
Vielleicht sollten die render lines in den html body?
