### ISSUE TITLE
Personal group gets overridden

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#290]
After each change of the permissions, the personal group is set to the current user. This is a problem if another person (via the 'can_manage' permission) changes the permission. Thus, the other person becomes the new 'owner'

### Dependencies

Depends on:

- #179 
- #153 

### Acceptance Criteria

- [ ]  The personal group permission should be immutable and should not be reset after a permission change.

**Comment by gruendlich** [comment]
PR #357

**Comment by gruendlich** [comment]
Reviewed, waiting to be moved to PO-Review
