### ISSUE TITLE
Personal groups should be named after the member

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#291]
In order to have a clear communication about the owner of an item, the personal groups should be named after the member.

### Dependencies

Depends on:

- #179 

### Acceptance Criteria

- [ ]  Rename all existing personal groups (in Prod) to the member's name.
- [ ] Make sure that new personal groups have the member's name.

**Comment by phkeese** [comment]
In progress [tr/rename-personal-groups](https://github.com/hpi-swt2/bookkeeper-portal-red/tree/tr%2Frename-personal-groups)
TODO: 
- [ ] Write code to set personal group name on creation (maybe in validator for group?)
- [ ] Test names of new personal groups
