### ISSUE TITLE
Implement basic asset structure and CRUD operations

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#30]
As a User I want to create, update and delete Assets. Therefore basic CRUD operations should be implemented.
Every Asset should contain the following attributes:
- id
- name
- description
- owner id
- owner name

### Dependecies
none

### Definition of Done
- [x] I am able to create assets using api calls.
- [x] I am able to update or delete assets identified by an unique key (using api calls).
- [x] The asset data structure contains the above attributes.

**Comment by gwauge** [comment]
- didn't implement owner relationship, as owner data model hasn't been defined yet --> should be a new issue when dependencies are cleared up
- also currently no support for variable attributes, implementation is still being discussed but might not be implemented in the desired form
