### ISSUE TITLE
Add Create Asset Web Page

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#31]
As a User I want to use a web page to create new assets. 
This web page should contain a form allowing to set values for every attribute of the asset.

### Dependencies
- #30 

### Defintion of Done
- [ ] A web page can be called containing input fields specific to the asset type.
- [ ] When the form is sent, a database entry for this asset is created.

**Comment by Glitterrosie** [comment]
5 SP
