### ISSUE TITLE
Add Web Page to edit one asset.

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#32]
As I user I want to be able to edit an existing asset. Therefore a similar screen to the insert screen (#31) should implemented to edit assets. 
Two buttons on the bottom of the screen allow to _1. reset do default_ or _2. Save_

### Dependecies
#30 
#31 

### Definition of Done
- [ ] I am able to open an edit web page with an asset id as a parameter.
- [ ] The edit screen should show the current data of an asset in an editable way (eg. Text Input)
- [ ] Saving with button 2 writes changed values into the database
- [ ] Button 1 resets input to previous values. Nothing in database is changed.

**Comment by Glitterrosie** [comment]
5 SP
