### ISSUE TITLE
Add a search functionality

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#34]
As a User I want to search assets by their name. Therefore a text search should be implemented. After entering a keyword every possible match should be displayed (#33). The name and description are searched.

### Dependecies
#33 

### Acceptance Criteria
- [ ] When entering a keyword all matching assets are shown in a grid view underneath.

**Comment by Glitterrosie** [comment]
13 SP

**Comment by gwauge** [comment]
Resolved by #139
