### ISSUE TITLE
Presentation: Prepare technical insights part

### ISSUE THREAD

**Issue by leonardhorns** [hpi-swt2/bookkeeper-portal-red#349]
As in the intermediate presentation, we want a technical insights part for the final presentation. In contrast to last time it should be a high level topic.
_Please choose one of the following:_

**1. Application architecture, functional components and libraries
2. Data organization and persistence, extensibility of data schemes
3. UI concepts employed, User Experience strategy & accessibility**

(~7 min)

The presentation is on 06.02., you can find the slides [here](https://docs.google.com/presentation/d/1IjyQyxHPuxxQxzlfFi0tAFhfKYm5mUNT3IAWK_PsX60/edit#slide=id.p2).

**Comment by DieKautz** [comment]
> _Please choose one of the following:_
> 
> **1. Application architecture, functional components and libraries
> 2. Data organization and persistence, extensibility of data schemes
> 3. UI concepts employed, User Experience strategy & accessibility**

Sollen davon alle drei Punkte abgedeckt werden oder eines davon besonders hervorgehoben?
