### ISSUE TITLE
Remove duplicate item description

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#351]
As a User of bookkeeper red I do not need the same description of an item twice. Therefore, remove the description on the left side (red box).

![grafik](https://user-images.githubusercontent.com/63072611/214586443-e9733410-0e5e-4b45-a6c9-bd51ec224315.png)

### Acceptance Criteria

- [ ] Only one description for one item. The description should be displayed on the right side.

**Comment by Ngo-Tuan-Kiet** [comment]
This issue should be fixed already (#300). At least under the [Development App](https://bookkeeper-red-dev.herokuapp.com/), I only see one description.

**Comment by FSadrieh** [comment]
Duplicated
