### ISSUE TITLE
Presentation: Demo

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#359]
Vorstellung soll 10 Minuten einnehmen. Der Fokus soll auf neuen Features liegen, die zu Zwischenpräsentation noch nicht gezeigt wurden (Gruppen, Permissions, Bilder, Warteliste).

Mit einer Art Rollenspiel könnten die Features anschaulich und realistisch demonstriert werden. 

Der Kunde hat den expliziten Wunsch geäußert, dass mit realistischen Items demonstriert wird. Also nicht 'Beispielbuch 1', sondern echte Bücher, Filme und Spiele, mit korrekt gepflegten Eigenschaften.

**Comment by DefineDan** [comment]
### Preparation

We need two separate users, one using the laptop U1, one using the phone U2, both connected using chrome devtools.
Prepare localhost instead of production version in case HPI internet fails.
Create 2 to 3 realistic items with real data.

### Groups
1. Create Group G (U1)
2. Edit item I permissions so that new group G can manage(U1)
3. Add User U2 to Group (U1)
5. Show updated permissions for item I (U2)
6. Edit item permissions so that new group G can only lend(U1)
7. Show updated permissions for item I (U2)

### New lending process features
1. Reserve Item (U2)
2. Join Waitlist (U1)
3. Lend and return item (U2)
4. Show Autoreservation caused by waiting list (U1)
8. Freeze Item (U1)
9. Show notifications in between

### Other features ?
1. Search Filters
2. New pages
3. CSV export
4. Analytics

**Comment by konrad-gerlach** [comment]
Rollen:
MobileUser WiMi
MobileUser oder PCUser Studi
PCUser ProfessorDr
Narrator?!

Konzeption (nicht Ablauf!):
	Man richtet die Lehrstuhlgruppe (ChairGroup) ein, dazu gehört der ProfessorDr und der WiMi, diese hat borrowing Rechte auf den Spielen 
	Man richtet die Lehrstuhlverwaltungsgruppe (ChairMgmtGroup) ein, dazu gehört der ProfessorDr, diese hat managing Rechte auf den Spielen & Büchern
	Item, welches von der Lehrstuhlgruppe geliehen werden kann: Werwolf
	Item, welches von allen geliehen werden kann (everyone): Design Patterns

Ablauf: ProfessorDr erstellt die beiden Items & druckt deren QR Codes aus (Geschieht alles im Voraus, die Items werden am Anfang gezeigt). Everyone hat view Rechte auf Werwolf. Everyone hat Borrowing Rechte auf Design Patterns.

On Screen: ChairGroup erstellen & WiMi hinzufügen; ChairGroup erhält Borrowing Rechte auf Werwolf (sonst keiner) 
Zeigen: Studi kann Werwolf nicht ausleihen.

WiMi leiht sich Werwolf aus.

Item Freeze & Reservierung & Management Rechte
ProfessorDr richtet die ChairMgmt Gruppe ein und transferiert Management Rechte an den beiden Items an die Gruppe.
WiMi möchte in die ChairMgmt wird in die ChairMgmt Gruppe aufgenommen werden.
WiMi freezed nun das Design Patterns Buch.
Der Studi kann es sich nicht mehr ausleihen und landet auf der Warteliste.
WiMi unfreezed Design Patterns.
Studi hat automatisch die Reservierung für Design Patterns.
WiMi versucht Design Patterns auszuleihen und landet auf Warteliste.
Studi scannt QRCode und leiht Design Patterns aus.
Studi gibt Design Patterns zurück, WiMi hat Reservierung auf Design patterns.

WiMi returniert Werwolf.


Setup:
	Gruppen:
		
	Items:
		Buch1:
			name: Design Patterns. Elements of Reusable Object-Oriented Software.
			ISBN: 978-0201633610
			Autor: Erich Gamma, Richard Helm, Ralph E. Johnson, John Vlissides
			Erscheiningsdatum: 01.07.197
			Genre: IT, Sachbuch
			Sprache: Englisch
			Seitenzahl: 395
			Verlag: Prentice Hall
			Edition: 1
		Spiel1:
			name: Werwölfe von Düsterwald
			beschreibung:  Die Werwölfe von Düsterwald Der kommunikative Gesellschaftsspiel-Klassiker  Auf einer zerklüfteten Hochebene des Hunsrücks liegt das kleine Dorf Düsterwald. Seit einiger Zeit wird das Dorf jede Nacht von Werwölfen heimgesucht; jede Nacht geschieht ein Verbrechen und ein Dorfbewohner fällt den Werwölfen zum Opfer.  Die Dorfbewohner versuchen herauszufinden, wer unter ihnen zu den Werwölfen gehört, bevor sie alle verschwinden!  Die Werwölfe von Düsterwald ist ein sehr kommunikatives und interaktives Kartenspiel für größere Runden oder Partys.
			Autor: des Pallières, Philippe
			Verleger: Asmodee
			Jugendfreigabe: 10
			Spielerzahl: 8-18
			Spieldauer: 20-40
			Sprache: Deutsch

**Comment by richartkeil** [comment]
- nur eine Chair Gruppe erstellen
- zusätzlich ein neues Item: das ist bereits von Student ausgeliehen, am Ende zeigt Studi dass er Overdue-Notification bekommen hat → gibt sein noch ausgeliehenes Item per Owner Return an WiMi zurück
- ganz am Ende schaut sich Prof. die History des Design Pattern Buchs an

**Comment by richartkeil** [comment]
## Prep:

### Sonntag:

- [x] Wizard Spiel erstellen (Everyone-View)
- [x] Overdue Item erstellen (Herr der Ringe Film)
- [x] Notification Overdue Item
- [x] Design Patterns Buch erstellen (Everyone-Borrow)
- [x] Ausleihen für Buch erstellen für History
- [x] QR Codes mit `172.20.10.2` erstellen für Buch und Spiel
- [x] Profile Description Tony und Tim und Johanna
- [x] weitere Items einstellen
- [x] Standorte für Items einstellen

### Kurz vor Präsentation

- [x] schönes Bild von Wizard machen und die anderen beiden löschen
- [ ] ~~Bild von Design Patterns Buch auf Richards Handy machen~~
- [x] QR Codes ausdrucken
- [x] Iphone Auto-Lock ausstellen und Auto-Rotate ausstellen
- [x] In Profile Page starten (Tony und Tim)
- [x] Tabs Camera und Safari, sonst alle schließen

### Nach Demo ggf. zurücksetzen:
- [ ] Gruppe löschen
- [ ] Berechtigungen zurücksetzen
- [ ] Lending von Tim für Design Patterns löschen
- [ ] Lat/Lng von Buch zurücksetzen (52.3935465 13.1318575)
- [ ] Bild von Buch löschen

## Ablauf:

- N:
  - willkommen zur Demo!
  - befinden uns am HPI, am Lehrstuhl für Big Data Management von Frau Prof. Schlimme
  - der Lehrstuhl kämpft seit Jahren mit Chaos beim Verleih von Büchern, Educational Software und anderen Gegenständen
  - niemand weiß wer etwas ausgeliehen hat, wo sich Items befinden oder wer auf Gegenstände wartet
  - doch nun hat Prof. Schlimme von einem neuen, modernen Tool gehört: "Bookkeeper Portal Red“ 
  - sie hat das direkt aufgesetzt — schauen wir doch mal rein wie das so läuft
- Prof: Das Einstellen meiner Items neulich war echt einfach. Nun hat mir jemand erzählt, dass ich auch Gruppen einrichten kann, um einige Items nur innerhalb dieser zugänglich zu machen. Dann werde ich jetzt mal eine Gruppe für meinen Lehrstuhl erstellen.
- _[Prof erstellt Gruppe "Intelligente Systeme" und fügt Wimi hinzu]_
- Tony: Hey Johanna, ich habe gesehen dass unser Design Patterns Buch ausgeliehen werden kann. Ich hab ein cooles Bild, könntest du mich als Manager hinzufügen damit ich das ändern kann? Außerdem würde ich gern Werwolf ausleihen.
- Prof: Ja klar, dann gebe ich einfach dem Lehrstuhl die Management Rechte für das Buch und allen aus dem Lehrstuhl die Rechte um Werwolf auszuleihen.
- _[Prof editiert Buch und fügt Chair Gruppe mit Management Permission hinzu und Everyone mit Borrowing Permissions]_
- _[Prof editiert Spiel und fügt Chair Gruppe mit Borrow Permissions hinzu]_
- Tony: Cool, dann leih ich mir das Spiel direkt aus. (**Bildschirm auf Handy switchen**)
- _[Tony scannt Spiel Code und leiht Spiel aus]_
- Tony: Dann füge ich hier das Bild hinzu
- _[Tony fügt Bild hinzu]_
- Tony: Oh, nur noch eine Woche bis zur Klausur, dann freeze ich doch mal das Buch – die Studis sind ja sicher schon bestens vorbereitet 😈
- _[Tony freezed Buch]_
- N: Es begibt sich nun, dass der bestens vorbereitete Studi Tim nun feststellt, dass die Klausur in einer Woche ist. Er hat nun erhöhtes Interesse an Lehrmaterial und möchte das Buch ausleihen.
- Tim: Wo finde ich denn das Design Patterns Buch? 
- _[Tim sucht nach Buch, findet es, schaut auf Standort]_
- Ach da, oh nein, unavailable! Dann muss ich wohl auf die Warteliste.
- _[Tim setzt sich auf Warteliste]_
- Tim: Ich geh mal beim Lehrstuhl vorbei und frag was da los ist. (geht hin)
- Tony: Hey Tim! Na, bist du schon gut auf die Klausur vorbereitet? *wink wink*
- Tim: Ja, ich würde gern nochmal das Design Patterns ausleihen, aber das ist gerade unavailable. Meinst du da lässt sich was machen?
- Tony: Naja... eine Woche vor Klausur geben wir das Buch eigentlich nicht mehr raus. Aber du warst ja so ein guter Studi, da kann ich mal ein Auge zudrücken ;)
- _[Tony unfreezed Buch]_
- Tim: Ah cool, jetzt habe ich auch direkt eine Reservierung weil ich vorhin auf der Warteliste stand. Dann leihe ich das jetzt mal aus.
- _[Tim leiht Buch aus]_
- N: Scheint so als sind erstmal alle happy. Springen wir nun 1 Woche in die Zukunft ...
- Tony: So! Ich hatte viel Spaß mit meinem Werwolf Spiel. Ich werd das mal zurückgeben, mal schauen was ich sonst noch so ausgeliehen habe.
- _[Tony sieht dass er ein Overdue Item hat, schaut auf Handy]_
- Tony: Oh, hab ich da keine Email bekommen? [zückt Handy, zeigt darauf] Doch natürlich... die hab ich wohl übersehen
- _[Tony gibt Werwolf per Owner Return an Johanna zurück]_ (**Bildschirm zurück auf Prof switchen**)
- Johanna: Na mal sehen, wer jetzt alles noch das Design Pattern Buch ausgeliehen hat
- _[Johanna checkt Historie]_
- Johanna: Ach, das hat ja alles super geklappt mit diesem neuen Tool. Das behalten wir doch gleich. Und jeder der das Buch ausgeliehen hat bekommt ne 1. Bookkeeper Portal Red empfehle ich direkt allen anderen Profs am HPI.

**Comment by DefineDan** [comment]
Im Kundengespräch kam nochmal der Wunsch, dass bei der Demo die ganze App ein wenig mit Leben gefüllt ist. Das heißt es wäre cool, wenn ihr zusätzlich zu den 2 Items, die wir für die Demo benutzen, 3-4 weitere Items (mit echten Daten und Bildern) in der App rumliegen habt und vielleicht auch noch 1 oder 2 Gruppen dazu passende Gruppen.

**Comment by DefineDan** [comment]
Falls ihr den Localhost benutzt, gibt es gerade noch einen Bug beim scannen vom item, der gerade gefixt wird: #399
