### ISSUE TITLE
Add Return Process: Owner return

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#38]
As an owner of an item, I want to be able to return a borrowed item of mine by myself. For that, I will have a button on the item details page that says "Returned", only when the item is borrowed by someone else. When I click this button, I (the lender) return the item instead of the borrower. This can be useful if the borrower personally returns me the item and I want to return it "officially".

### Dependencies

- #8 
- #16 
- #30 

### Acceptance Criteria
- [x] Button "Returned" on Item details page only if user can manage item and item is borrowed by another user
- [x] "Returned" Button click, returns the item, making it available for everyone else again
- [x] When using the "Returned" button, the borrower doesn't return again

**Comment by Tonybodo** [comment]
Review ist abgeschlossen und auf Dev gemerged. Die einzige Frage ist wie dem Tracking der zurückgebenden Verfahren werden soll und ob das Naming der Button passt. Tim und ich sind der Meinung, dass das Anpassen des Datenmodells eigentlich Aufgabe der Leute ist, die für die Ausleihhistorie verantwortlich sind. In meinem Code müsste weiterhin wahrscheinlich nur eine Zeile angepasst werden. Außerdem habe ich unter dem Issue für die Ausleihhistorie einen entsprechenden Kommentar verfasst.

**Comment by Tonybodo** [comment]
@DefineDan How do we continue with the issue?

**Comment by DefineDan** [comment]
@Tonybodo moved it to #265 with lower prio. We can close this issue.
