### ISSUE TITLE
Broken alignment on mobile on the qr code 

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#383]
As a user of bookkeeper red, I prefer a device-friendly design. Therefore, the qr-code should not overreach the screen on a mobile device.

![grafik](https://user-images.githubusercontent.com/63072611/216126296-960ce074-878e-49bf-9e46-2c9370fec9bf.png)

### Acceptance Criteria

- [ ]  The QR-Code frame should fit the screen size of the device. The entire nav-bar and footer should be visible.

**Comment by Pungitius** [comment]
why should the footer be visible?

**Comment by Alorcus** [comment]
> why should the footer be visible?

So that the whole appearance is simply coherent. The QR code window doesn't have to be unnecessarily large.
Or what do you think? Is displaying the footer a problem?
