### ISSUE TITLE
Permissions are stored twice by mistake

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#398]
At the moment, permissions get saved twice or more. This should not be the case.

Permissions of an item before update:
![grafik](https://user-images.githubusercontent.com/63072611/216563505-32f99804-d4e3-4d0e-a3e2-b21a5f728928.png)
Permissions of an item after update:
![grafik](https://user-images.githubusercontent.com/63072611/216563728-8d2939e8-1fbf-45dd-8cc6-55c14711bef1.png)

### Acceptance Criteria

- [ ]  Permissions should not be duplicated after an object is updated.

**Comment by MaxSpeer** [comment]
Mit der Änderung erscheinen die Permissions zwar nicht doppelt. Löschen kann man sie aber leider immer noch nicht.

**Comment by MatthiasCr** [comment]
@MaxSpeer Mmh das kann ich leider nicht replizieren. Könntest du beschreiben wann das Problem bei dir auftritt? Wenn ich eine Permission hinzufüge bspw. GruppeX  "can_manage", dann erscheint GruppeX danach auch als owner. Wenn ich diese dann wieder lösche, ist auch der owner weg. In der Datenbank existiert die permission dann auch nicht mehr, gleiches bei "can_borrow" und "can_view". (getestet auf dem aktuellen dev, auf main wurden diese Änderungen noch nicht gepushed)

**Comment by MaxSpeer** [comment]
Ich glaube ich war auf dem falschen branch. Auf dev sieht es doch gut aus. Danke Dir!
