### ISSUE TITLE
Add a login screen for mobile

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#41]
As a user, I want to be able, to have site on mobile where I can login, so that the login process is facilitated.

For Mock-Up scroll down

### Dependencies

- none

### Definition of Done

- [ ] a dedicated site where I can login with my HPI-Email (HPI OpenID Connect; path should be something like [url.de]/login) exists
- [ ] the style matches the theme of HPI/ Mock-Ups

Example Login with Tele-Task on mobile:

![Image](https://user-images.githubusercontent.com/66786380/201766141-1308a247-1448-4a84-9815-3bab86d7fa47.png)

![Image](https://user-images.githubusercontent.com/66786380/201766196-7fb861f1-7f16-47e7-bc98-7b44e69929a9.png)

Homescreen of website (for style orientation):

![Image](https://user-images.githubusercontent.com/66786380/201766433-651dab80-996e-436d-a8a3-d8dbaeb99f8d.png)

![Image](https://user-images.githubusercontent.com/66786380/201766477-d9a3eaca-eca7-4041-a286-03c07c22a6d3.png)

Colors to use:

![Image](https://user-images.githubusercontent.com/66786380/201765751-31bae738-8b44-409c-a61a-e4497612f844.png)

**Comment by Skn0tt** [comment]
addresses by https://github.com/hpi-swt2/bookkeeper-portal-red/pull/62
