### ISSUE TITLE
Add a profile page on mobile

### ISSUE THREAD

**Issue by Ngo-Tuan-Kiet** [hpi-swt2/bookkeeper-portal-red#42]
As a user, I want to have a dedicated profile site on mobile, so that I can easily access/edit my provided informations and so that other users can easily identify me.

For Mock-Up scroll down

### Dependencies

- #19 

### Definition of Done

- [ ] a site solely dedicated to my profile (path should be something like "[url.de]/user/me" or maybe something like HPI-Moodle "https://moodle.hpi.de/user/profile.php?id=1216")
- [ ] the style matches the theme of HPI/ Mock-Ups
- [ ] my full name is visible
- [ ] ~I can edit my name~
- [ ] my HPI-Email is visible

Mobile Mock-Up:

![Image](https://user-images.githubusercontent.com/66786380/201766829-92db560d-1720-4233-a1ed-cf5eacb9cd8d.png)

**Comment by phkeese** [comment]
Hey @Ngo-Tuan-Kiet , are we still doing the "edit my name" task?

**Comment by Skn0tt** [comment]
>  I can edit my name

As we discussed yesterday, we'll keep this out of scope for now. Names will hopefully be pulled from OIDC, so there's no need for edits.
