### ISSUE TITLE
Check lending permissions

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#69]
As a User, I can only borrow items, if I am part of a group, which is allowed to borrow the item.

### Dependencies

Depends on:

- #8 
- #65 
- #5

### Acceptance Criteria

- [ ] The lending button is only visible, if the user has the right to borrow the item.
- [ ] I<del> f a user is not authorized to borrow an item, the "No access" status is displayed in the preview of the item. <del>

**Comment by DefineDan** [comment]
@Tonybodo Das ist schon implementiert oder?

**Comment by Tonybodo** [comment]
Ja aktuell können Items nur ausgeliehen werden, wenn eine Gruppe in der der User drin ist mit einer Gruppe des Items übereinstimmen.

**Comment by Alorcus** [comment]
Good to know!
My Team works on the lending permission in #65. I think to check if the permission is well implemented, it would be good, if my team can keep this ticket.

**Comment by DefineDan** [comment]
Ok, but do you also want to do the UI part: 'If a user is not authorized to borrow an item, the "No access" status is displayed in the preview of the item' since as I said we are doing something very similar

**Comment by DefineDan** [comment]
Ok moved this to #151

**Comment by Tonybodo** [comment]
Why this issue is still open? The feature has been implemented over a month ago.  @DefineDan @Alorcus

**Comment by Alorcus** [comment]
@WilliamBrandt Maybe you can give us more information there?

**Comment by WilliamBrandt** [comment]
Yes i checked its done. Sorry i forgot to move it
