### ISSUE TITLE
Create "my groups" webpage

### ISSUE THREAD

**Issue by Encotric** [hpi-swt2/bookkeeper-portal-red#7]
As a user, I want to see my own group memberships and their current listings under domain.tld/groups. I also want a button to leave a group for each listed group membership on this page to manage my current memberships easily. Moreover, I want to have the ability to create a group on my own using a button on top of the page. After clicking this button, I would like to have a modal window where I can enter my desired group name and submit my group creation.

### Dependencies

Depends on:

- #5
- #30

### Acceptance criteria

- [x] UI design and layout for group memberships: see wireframes down below
- [x] Connected to group management implementation in the backend
- [x] Screens:
    - [x] Group memberships overview
- [x] clicking on "Meine Gruppen" in the navigation bar redirects to this page

![My groups page](https://user-images.githubusercontent.com/27862794/202265276-3e3635ee-2dcb-455f-afc4-cd7d0fd11720.png)

![Group creation screen](https://user-images.githubusercontent.com/27862794/202268506-11ed7c9a-2e8c-453a-83b6-860224fdc1c6.png)

**Comment by DieKautz** [comment]
will be worked on in #116

**Comment by DieKautz** [comment]
leave group button could be aligned just as the group owners edit button
(no quick and easy solution found with bootstrap/css)
