### ISSUE TITLE
Check visibility permissions

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#75]
As a User, I can only see items, if I am part of a group, which is allowed to see the item.

### Dependencies

Depends on:

- #33
- #34
- #5 
- #153 
- #76

### Definition of Done

- [ ]  The item is only visible, if the user has the right to see the item.
- [ ] The item is not shown in the search and in the main asset page

**Comment by Tonybodo** [comment]
Für das testen könnt ihr wie immer in das User Modell folgenden Code in die can_view? Methode einfügen:
```testGroup = Group.new(name: "Test Group")
testGroup.save
testMembership = Membership.new(role: 1, user_id: id, group: testGroup)
testMembership.save

item_groups = item.viewer_groups
user_memberships = memberships
user_memberships.push(testMembership)
user_groups = groups
item_groups.push(testGroup)```

**Comment by DefineDan** [comment]
@Tonybodo Können wir das mit den can_view permissions so machen, dass wenn für ein Item keine can_view Gruppen gesetzt sind, ALLE das Item sehen dürfen. Sobald can_view explizit für Gruppen gesetzt wird, sind nur diese Gruppen berechtigt das Item anzusehen?

**Comment by Tonybodo** [comment]
Um vielleicht nochmal genauer den eigentlichen Workflow zu beschreiben. Nach dem aktuellen Datenmodell sollte es eine Gruppe geben in der alle User drin sind. Bei der Erstellung des Items könnte man dann default mäßig das Item dieser Gruppe hinzufügen und die Permission can_view geben. Alternativ könnte man evtl. auch über die personal groups der Nutzer gehen die es ja mitlerweile gibt, aber das wäre unschön und nur ein Mittel zum Zweck. Push lieber mal die anderen Teams, dass sie sich voll auf das setzen der Gruppen etc. konzentrieren.

**Comment by DefineDan** [comment]
Ok es wäre nur wichtig, dass es einfach ist, das Item für alle sichtbar zu machen. Also nicht dass ich da alle Gruppen einzeln auswählen muss. Aber ja, da sollten sich vermutlich die Leute Gedanken machen, die die Gruppen für die Rechte bei der Erstellung auswählen.
