### ISSUE TITLE
Set item visibility permissions

### ISSUE THREAD

**Issue by FSadrieh** [hpi-swt2/bookkeeper-portal-red#76]
As an item owner, I can choose groups, which are allowed to see the item. I can do that, when I am creating or editing an item.

Depends on:

- #56 
- #32

### Definition of Done

- [ ] Every group is available.
- [ ] It's possible to select more than one group.
- [ ] It's possible to remove a chosen group.

**Comment by Alorcus** [comment]
Deprecated. #153 unifies permission logic
