### ISSUE TITLE
Create Asset Details Screen

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#8]
As a user, I want to have a separate page for each asset entity under the route /asset/<asset_id>. On this page I will see the attributes, the owner and the status of the asset. I will have action buttons according to the asset status and my role.

### Dependencies
- #30 
- #16 
- Asset data model
- Roles model (ownership)

### Definition of Done
- [ ] Detail screen for every asset in the system with described elements
- [ ] UI design and layout according to wireframes 
- [ ] Conditional Logic for action buttons

![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63105659/201534961-1e0c19c3-3970-4d8f-a6ba-c8ca0d6f72cf.png)

![Full HD](https://user-images.githubusercontent.com/63105659/201534905-94a6a000-e3b5-4ecc-b3fe-bac366148612.png)

**Comment by konrad-gerlach** [comment]
Dieses Issue fügt UI Tests hinzu, die eine Chrome installation benötigen und damit z.B. nicht in der WSL laufen. In der CI wurden sie bereits deaktiviert. Lokal können sie mit dem Befehl `bundler exec "rspec --tag ~ui" ` beim Ausführen der Tests deaktiviert werden.
