### ISSUE TITLE
Check management permissions

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#86]
As a User, I can edit an item, if I am part of a group, which is allowed to manage the item.

### Dependencies

Depends on:

- #85 
- #32 

### Acceptance Criteria

- [ ]  The user gets access to the edit screen (#32), if the user has the permission to manage the item.

### Storypoints
8

**Comment by DefineDan** [comment]
Is this still active or can we close it?

**Comment by codingWhale13** [comment]
Good point!

It can be closed as it's part of issue #128. Closing it now.
