### ISSUE TITLE
Integrate grid view into home screen

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#89]
As A User I want to see every asset on the home screen in a grid view. Therefore the already implemented grid view should be integrated in the home screen. 

Acceptance Criteria:

- [x] The home screen includes a grid view showing every asset.

**Comment by MaxSpeer** [comment]
May dependent on: #29

**Comment by simon-weissmueller** [comment]
Items of every kind with a sane amount of items
