### ISSUE TITLE
Add Lending Process: Reservation

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#9]
As a user that wants to borrow an item, I can make a reservation before I pick it up (borrow it). During the reservation the item is unavailable for other users. If I exceed the maximal reservation duration my reservation expires and the asset is available for everyone again.

### Dependencies

Depends on:

- #8 
- #16 
- #30 

### Definition of Done

- [x] Available items can be reserved on the Item details page
- [x] Reserved items can not be reserved or borrowed by others
- [x] Reservation expires after max. reservation duration

![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63105659/201535115-6746d7e5-398b-4b07-bffa-588251bcbad1.png)
![iPhone 13 Pro Max](https://user-images.githubusercontent.com/63105659/201535131-13a0e279-4d57-4ce0-b3c4-041c1ea6f988.png)

**Comment by Tonybodo** [comment]
Wenn auf reservieren geklickt wird, gilt ab sofort und mit festgelegter Größe. 
Man sieht nie beide Buttons gleichzeitig. Wenn der QR Code gescannt wird Ausleih Button, sonst reservieren Button.
max reservation ist ungleich borrow period.

**Comment by TimRiedel** [comment]
Somebody can reserve an item if:

- [ ] the item is lendable
- [ ] no reservation exists by others
- [ ] he/she has lending rights

**Comment by konrad-gerlach** [comment]
- [ ] Ensure All necessary attributes for item creation are specified when creating new item (validate attributes!)

**Comment by TimRiedel** [comment]
Erklärung der Methodennamen:
- `item.reserved?: Es gibt eine aktive Reservierung für das Item (egal von welchem User), Ausleihen werden ignoriert
- `item.not_reserved?`: Negation
- `item.borrowed?`: Es gibt eine aktive Ausleihe für das Item (egal von welchem User), Reservierungen werden ignoriert
- `item.not_borrowed?`: Negation

- `item.current_reservation`: Die aktive Reservierung, falls vorhanden, sonst `nil`
- `item.reservable_by?(user)`: Das Item ist nicht ausgeliehen, es gibt keine aktiven Reservierungen und der Nutzer hat Ausleihrechte
- `item.reserved_by?(user)`: Das Item ist momentan vom Nutzer reserviert

- `item.borrowable_by?(user)`: Das Item ist nicht ausgeliehen, es gibt keine aktiven Reservierungen von anderen Nutzern und der Nutzer hat Ausleihrechte
- `item.borrowed_by?(user)`: Das Item ist momentan vom Nutzer ausgeliehen

- `user.lending_rights?(item)`: Der Nutzer hat Ausleihrechte

**Comment by richartkeil** [comment]
Re-Estimation: M
(for writing tests and max_reservation_days)

**Comment by richartkeil** [comment]
Review by @Tonybodo
