### ISSUE TITLE
Ask for item type on item creation

### ISSUE THREAD

**Issue by MaxSpeer** [hpi-swt2/bookkeeper-portal-red#93]
As a User I want to specify the Items type on Item creation. Therefore a drop down menu should be displayed after clicking "create item". The drop down menu contains every available item type. Clicking an Item type leads to the insert page of that item type.

Acceptance Criteria:

- [x] A drop down menu opens when clicking on the "create item" button.
- [x] Clicking on the item type opens the insert page of that item type.

**Comment by MaxSpeer** [comment]
Could depend on #92

**Comment by Glitterrosie** [comment]
i think you mean the new item button?
